//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Binding.MSMQ.Mail.Client.WPF.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.class-a.nl/msmq/example01/2008/02/", ConfigurationName="Service.ISendMail", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
    public interface ISendMail {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://schemas.class-a.nl/msmq/example01/2008/02/ISendMail/SubmitMessage")]
        void SubmitMessage(Binding.MSMQ.Mail.Common.MailMessage message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://schemas.class-a.nl/msmq/example01/2008/02/ISendMail/SubmitMessage")]
        System.Threading.Tasks.Task SubmitMessageAsync(Binding.MSMQ.Mail.Common.MailMessage message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISendMailChannel : Binding.MSMQ.Mail.Client.WPF.Service.ISendMail, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendMailClient : System.ServiceModel.ClientBase<Binding.MSMQ.Mail.Client.WPF.Service.ISendMail>, Binding.MSMQ.Mail.Client.WPF.Service.ISendMail {
        
        public SendMailClient() {
        }
        
        public SendMailClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendMailClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendMailClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendMailClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SubmitMessage(Binding.MSMQ.Mail.Common.MailMessage message) {
            base.Channel.SubmitMessage(message);
        }
        
        public System.Threading.Tasks.Task SubmitMessageAsync(Binding.MSMQ.Mail.Common.MailMessage message) {
            return base.Channel.SubmitMessageAsync(message);
        }
    }
}
